### PR TITLE
Bumping version, adding debian init file, movig vars

### PR DESCRIPTION
**Pull request by mbolek**
Changes to be committed:
	copied:     vars/main.yml -> defaults/main.yml
	new file:   templates/blackbox-exporter.sysvinit.debian.sh.j2
	modified:   vars/main.yml

### CODE REVIEW

**Comment by hgontijo** [comment]
Since you introduced support for Debian systems, could you please change `tasks/main.yml` accordingly to handle service configuration for Debian systems?
Thanks.

**Comment by mbolek** [comment]
Completely forgotten about that :)

**Comment by hgontijo** [comment]
Since `vars/main.yml` is not used anymore, could you just delete it?
Could you please also update the tests with the new file mode - `assert blackbox_config.mode == 0o644`?

**Comment by mbolek** [comment]
Of course. I wasn't sure if you'd like the file to be removed

**Pull request merged**
